#!/bin/bash

xinput set-prop "Synaptics TM3096-001" "Device Accel Constant Deceleration" 3

synclient VertScrollDelta=-47
synclient HorizScrollDelta=-47
synclient HorizTwoFingerScroll=1
synclient AccelFactor=0.05
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient PalmDetect=1
